source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '15.0'

target 'Rudder-Moengage_Example' do
  pod 'Rudder-Moengage', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
